{{- if .Values.plugin.enabled }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: replace
  name: mysqls.test.pandaria.io
spec:
  group: test.pandaria.io
  names:
    kind: MySQL
    plural: mysqls
    singular: mysql
    shortNames:
    - my
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              image:
                type: string
              replicas:
                type: integer
              storage:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
{{- end }}
